namespace MeidoPhotoStudio.Plugin.Framework;

/// <summary>
/// Provides version safe accessors for <c>MPN</c> enum members that are parsed at runtime.
/// </summary>
/// <remarks>Implementation is generated by source generator.</remarks>
[SafeEnum.SafeEnum<MPN>]
internal static partial class SafeMpn
{
}
