<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="..\..\lib\Assembly-UnityScript-firstpass.dll" />
    <Reference Include="../../ref/COM3D2.MaidLoader.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ionic.Zlib" Version="1.9.1.*" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.*" />
    <PackageReference Include="ValueTupleBridge" Version="0.1.5" />
    <PackageReference Include="TaskParallelLibrary.Repackaged" Version="1.0.4-custom" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="../MeidoPhotoStudio.Plugin.Analyzer/MeidoPhotoStudio.Plugin.Analyzer.csproj"
      ReferenceOutputAssembly="false"
      OutputItemType="Analyzer"
      SetTargetFramework="TargetFramework=netstandard2.0"
      />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Config/MeidoPhotoStudio/Translations/en/translation.ui.json" />
    <AdditionalFiles Include="Config/MeidoPhotoStudio/Translations/en/translation.props.json" />
    <AdditionalFiles Include="Config/MeidoPhotoStudio/Translations/en/translation.bg.json" />
    <AdditionalFiles Include="Config/MeidoPhotoStudio/Translations/en/translation.face.json" />
  </ItemGroup>

</Project>
